defalut_homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index

lista:
    path: /lista
    defaults:
        _controller: AppBundle:Default:lista

rezerwacja:
    path: /rezerwacja
    defaults:
        _controller: AppBundle:Default:rezerwacja

platnosc:
    path: /platnosc/
    defaults:
        _controller: AppBundle:Default:platnosc

potwierdzenie:
    path: /potwierdzenie
    defaults:
        _controller: AppBundle:Default:potwierdzenie

kontakt:
    path: /kontakt
    defaults:
        _controller: AppBundle:Default:kontakt

akceptacja:
    path: /akceptacja/{id_samochodu}
    defaults:
        _controller: AppBundle:Default:akceptacja